name: User Registration-1.11 CI/CD Pipeline

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Install Python dependencies
    - name: Install Python dependencies
      run: pip install -r requirements.txt

    # Set up Node.js environment for React frontend
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    # Install Node.js dependencies
    - name: Install Node.js dependencies
      run: npm ci

    # Build the React frontend
    - name: Build the React frontend
      run: npm run build

    # Run Python backend tests
    - name: Run Python backend tests
      run: pytest
